### ISSUE TITLE
Is it possible to evaluate using models from Azure OpenAI Service?

### ISSUE THREAD

**Issue by ayrtondenner** [hegelai/prompttools#83] opened 2023-08-21 22:34 UTC
### ⁉️ Discussion/Question

I have a model currently available via Azure OpenAI, is it possible to run a prompt through it passing AZURE_OPENAI_API_KEY instead of OPENAI_API_KEY for instance?

**Comment by NivekT** [comment] 2023-08-22 00:54
Hi @ayrtondenner, that definitely is a use case that we'd like to support.

I will look into it, but if someone wants to try implementing this, feel free to comment here.

**Comment by krrishdholakia** [comment] 2023-08-25 16:20
@ayrtondenner @NivekT I think we might be able to help - https://github.com/BerriAI/litellm

We support Azure, VertexAI, Replicate, Anthropic, Cohere, AI21, Huggingface, Baseten, TogetherAI 

I'll make a PR and see if that works for y'all?

**Comment by NivekT** [comment] 2023-08-25 17:16
@ayrtondenner We have updated our [`OpenAICompletionExperiment` API](https://github.com/hegelai/prompttools/blob/main/prompttools/experiment/experiments/openai_completion_experiment.py) to support Azure. Here is a [code example](https://github.com/hegelai/prompttools/blob/main/examples/notebooks/AzureOpenAICompletionExperiment.ipynb). 

Let us know how it is working for you. Happy to make further changes if you experience any issue. Feel free to open a PR to make changes as well.

I will follow up and update the ChatExperiment as well. If there is interest to support Azure within the playground, please comment and let us know.

**Comment by NivekT** [comment] 2023-08-27 06:51
@ayrtondenner  I can confirm that we have added support for Azure in both chat and text completion. Let me know if it is working for you. We would also love to chat about your use cases.

**Comment by ayrtondenner** [comment] 2023-08-28 11:23
Is that already added in the pip library? I just tried it in a new Colab notebook but it didn't work:

```python
TypeError: OpenAICompletionExperiment.__init__() got an unexpected keyword argument 'azure_openai_service_configs'
```

**Comment by NivekT** [comment] 2023-08-28 18:44
Hi @ayrtondenner, we have not pushed a new package but we will do that today. In the meantime, it is available if you install from source by cloning the GitHub repo.

**Comment by ayrtondenner** [comment] 2023-08-29 22:36
I got the following new error:

```python
from prompttools import utils

AttributeError                            Traceback (most recent call last)
[<ipython-input-4-aab89cdcb7ec>](https://localhost:8080/#) in <cell line: 4>()
      2 from prompttools.experiment import OpenAIChatExperiment
      3 
----> 4 from prompttools import utils

9 frames
[/usr/local/lib/python3.10/dist-packages/numpy/__init__.py](https://localhost:8080/#) in __getattr__(attr)
    309             return val
    310 
--> 311         if attr in __future_scalars__:
    312             # And future warnings for those that will change, but also give
    313             # the AttributeError

AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
```

**Comment by NivekT** [comment] 2023-08-29 22:54
Thanks for flagging that!

At a quick glance, I can't tell if it an issue with our library. Do you have more information? Are you running on Colab such that you can provide a reproducible script?

It may be a `numpy` issue similar to [this](https://github.com/vladmandic/automatic/issues/1149), can you update your `numpy` package? You may need a version > 1.21 .

As a workaround, you may be able to import the specific `utils` function that you need, rather than the whole submodule.

**Comment by NivekT** [comment] 2023-09-17 04:35
Hi @ayrtondenner, since this feature has been added. I will close this for now. Don't hesitate to comment or reach out if anything is not working for you!

**Closed by NivekT** 2023-09-17 04:35 UTC
Labels: enhancement, help wanted, good first issue
